/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Estructura;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Stack;

import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import com.DBConnection.DbConnection;
import com.Entidad.Producto;
import com.Entidad.Usuario;
import com.Pantallas.UtilPantalla;

/**
 *
 * @author mauri
 */
@SuppressWarnings("FieldMayBeFinal")
public class MenuPrincipal extends javax.swing.JFrame {

    private List<Double> numeros = new ArrayList<>();
    private List<String> operadores = new ArrayList<>();
    private double resultadoAnterior = 0;
    private boolean resultadoCalculado = false; // Para saber si ya se ha calculado un resultado

    private DbConnection dbConnection = new DbConnection();
    private UtilPantalla utilPantalla = new UtilPantalla();
    private List<Producto> productoList = new ArrayList<>();
    private List<Usuario> usuarioList = new ArrayList<>();

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {

        String rutaDirectorio = System.getProperty("user.dir");
        System.out.println("Ruta del directorio de trabajo: " + rutaDirectorio);
        

        dbConnection.conectarBaseDatos();
        usuarioList = dbConnection.consultarUsuarios();
        productoList = dbConnection.consultarProductos();
        initComponents();
        llenarTablaUsuarios();
        llenarTablaProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "Convert2Lambda" })
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenuPrincipal = new javax.swing.JPanel();
        jfMenuTabs = new javax.swing.JInternalFrame();
        jTabPanel = new javax.swing.JTabbedPane();
        jTabPanelProductos = new javax.swing.JScrollPane();
        jTabPanelRegistro = new javax.swing.JPanel();
        lblNombreProducto = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblUbicacionImg = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtUbicacionImgProducto = new javax.swing.JTextField();
        btnRegistrarProducto = new javax.swing.JButton();
        jTabPanelUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jpResumen = new javax.swing.JPanel();
        jfCalculadora = new javax.swing.JInternalFrame();
        jpOperaciones = new javax.swing.JPanel();
        jtxtOperaciones = new javax.swing.JTextField();
        jpResultados = new javax.swing.JPanel();
        jtxtResultados = new javax.swing.JTextField();
        btnRetroceso = new javax.swing.JButton();
        btnPorcentaje = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btnAC = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btn00 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1015, 801));

        jfMenuTabs.setVisible(true);

        jTabPanelProductos.setMaximumSize(new java.awt.Dimension(560, 750));
        jTabPanel.addTab("Productos", jTabPanelProductos);

        lblNombreProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombreProducto.setText("Nombre del Producto");

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrecio.setText("Precio");

        lblUbicacionImg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUbicacionImg.setText("Ubicacion imagen del Producto");

        txtNombreProducto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtUbicacionImgProducto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btnRegistrarProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistrarProducto.setText("Registrar Producto");
        btnRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTabPanelRegistroLayout = new javax.swing.GroupLayout(jTabPanelRegistro);
        jTabPanelRegistro.setLayout(jTabPanelRegistroLayout);
        jTabPanelRegistroLayout.setHorizontalGroup(
                jTabPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jTabPanelRegistroLayout.createSequentialGroup()
                                .addGroup(jTabPanelRegistroLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jTabPanelRegistroLayout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addGroup(jTabPanelRegistroLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtNombreProducto,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 510,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jTabPanelRegistroLayout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addComponent(lblNombreProducto,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(lblPrecio,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(lblUbicacionImg,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))
                                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtUbicacionImgProducto,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 510,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jTabPanelRegistroLayout.createSequentialGroup()
                                                .addGap(197, 197, 197)
                                                .addComponent(btnRegistrarProducto)))
                                .addContainerGap(39, Short.MAX_VALUE)));
        jTabPanelRegistroLayout.setVerticalGroup(
                jTabPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jTabPanelRegistroLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lblNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblUbicacionImg, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUbicacionImgProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(27, Short.MAX_VALUE)));

        jTabPanel.addTab("Registro De Productos", jTabPanelRegistro);

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null },
                        { null, null, null },
                        { null, null, null },
                        { null, null, null }
                },
                new String[] {
                        "ID", "Nombre de Usuario", "Contraseña"
                }) {
            Class[] types = new Class[] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableUsuarios);

        javax.swing.GroupLayout jTabPanelUsuariosLayout = new javax.swing.GroupLayout(jTabPanelUsuarios);
        jTabPanelUsuarios.setLayout(jTabPanelUsuariosLayout);
        jTabPanelUsuariosLayout.setHorizontalGroup(
                jTabPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE));
        jTabPanelUsuariosLayout.setVerticalGroup(
                jTabPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jTabPanelUsuariosLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                                .addContainerGap()));

        jTabPanel.addTab("Usuarios", jTabPanelUsuarios);

        javax.swing.GroupLayout jpResumenLayout = new javax.swing.GroupLayout(jpResumen);
        jpResumen.setLayout(jpResumenLayout);
        jpResumenLayout.setHorizontalGroup(
                jpResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 741, Short.MAX_VALUE));
        jpResumenLayout.setVerticalGroup(
                jpResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));

        javax.swing.GroupLayout jfMenuTabsLayout = new javax.swing.GroupLayout(jfMenuTabs.getContentPane());
        jfMenuTabs.getContentPane().setLayout(jfMenuTabsLayout);
        jfMenuTabsLayout.setHorizontalGroup(
                jfMenuTabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpResumen, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jfMenuTabsLayout.createSequentialGroup()
                                .addComponent(jTabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 593,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        jfMenuTabsLayout.setVerticalGroup(
                jfMenuTabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jfMenuTabsLayout.createSequentialGroup()
                                .addComponent(jTabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 492,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpResumen, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jfCalculadora.setVisible(true);

        jtxtOperaciones.setEditable(false);
        jtxtOperaciones.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jtxtOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtOperacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpOperacionesLayout = new javax.swing.GroupLayout(jpOperaciones);
        jpOperaciones.setLayout(jpOperacionesLayout);
        jpOperacionesLayout.setHorizontalGroup(
                jpOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtxtOperaciones));
        jpOperacionesLayout.setVerticalGroup(
                jpOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtxtOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE));

        jtxtResultados.setEditable(false);
        jtxtResultados.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N

        javax.swing.GroupLayout jpResultadosLayout = new javax.swing.GroupLayout(jpResultados);
        jpResultados.setLayout(jpResultadosLayout);
        jpResultadosLayout.setHorizontalGroup(
                jpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtxtResultados));
        jpResultadosLayout.setVerticalGroup(
                jpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtxtResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE));

        btnRetroceso.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRetroceso.setText("->");
        btnRetroceso.setPreferredSize(new java.awt.Dimension(77, 77));
        btnRetroceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocesoActionPerformed(evt);
            }
        });

        btnPorcentaje.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPorcentaje.setText("%");
        btnPorcentaje.setPreferredSize(new java.awt.Dimension(77, 77));
        btnPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcentajeActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn7.setText("7");
        btn7.setPreferredSize(new java.awt.Dimension(77, 77));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn8.setText("8");
        btn8.setPreferredSize(new java.awt.Dimension(77, 77));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btnDivision.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDivision.setText("/");
        btnDivision.setPreferredSize(new java.awt.Dimension(77, 77));
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        btnMultiplicacion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnMultiplicacion.setText("X");
        btnMultiplicacion.setPreferredSize(new java.awt.Dimension(77, 77));
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn4.setText("4");
        btn4.setPreferredSize(new java.awt.Dimension(77, 77));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn5.setText("5");
        btn5.setPreferredSize(new java.awt.Dimension(77, 77));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btnMenos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnMenos.setText("-");
        btnMenos.setPreferredSize(new java.awt.Dimension(77, 77));
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        btnAC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAC.setText("AC");
        btnAC.setPreferredSize(new java.awt.Dimension(77, 77));
        btnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACActionPerformed(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn1.setText("1");
        btn1.setPreferredSize(new java.awt.Dimension(77, 77));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn2.setText("2");
        btn2.setPreferredSize(new java.awt.Dimension(77, 77));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btnSuma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSuma.setText("+");
        btnSuma.setPreferredSize(new java.awt.Dimension(77, 77));
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btn0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn0.setText("0");
        btn0.setPreferredSize(new java.awt.Dimension(77, 77));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnPunto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPunto.setText(".");
        btnPunto.setPreferredSize(new java.awt.Dimension(77, 77));
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        btnIgual.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnIgual.setText("=");
        btnIgual.setPreferredSize(new java.awt.Dimension(77, 77));
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btn00.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn00.setText("00");
        btn00.setPreferredSize(new java.awt.Dimension(77, 77));
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn3.setText("3");
        btn3.setPreferredSize(new java.awt.Dimension(77, 77));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn6.setText("6");
        btn6.setPreferredSize(new java.awt.Dimension(77, 77));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn9.setText("9");
        btn9.setPreferredSize(new java.awt.Dimension(77, 77));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jfCalculadoraLayout = new javax.swing.GroupLayout(jfCalculadora.getContentPane());
        jfCalculadora.getContentPane().setLayout(jfCalculadoraLayout);
        jfCalculadoraLayout.setHorizontalGroup(
                jfCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpResultados, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jfCalculadoraLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jfCalculadoraLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jfCalculadoraLayout.createSequentialGroup()
                                                .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jfCalculadoraLayout.createSequentialGroup()
                                                .addGroup(jfCalculadoraLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jfCalculadoraLayout.createSequentialGroup()
                                                                .addGap(83, 83, 83)
                                                                .addComponent(btn1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 77,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btn2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btn3,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jfCalculadoraLayout.createSequentialGroup()
                                                                .addComponent(btnPorcentaje,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 77,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btn4,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 77,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btn5,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btn6,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jfCalculadoraLayout.createSequentialGroup()
                                                                .addComponent(btnRetroceso,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btn7,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 77,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btn8,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btn9,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(12, 12, 12)
                                                .addGroup(jfCalculadoraLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnDivision,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnMultiplicacion,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 77,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(12, Short.MAX_VALUE)));
        jfCalculadoraLayout.setVerticalGroup(
                jfCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jfCalculadoraLayout.createSequentialGroup()
                                .addComponent(jpOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpResultados, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(jfCalculadoraLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnRetroceso, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jfCalculadoraLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jfCalculadoraLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jfCalculadoraLayout.createSequentialGroup()
                                                .addGroup(jfCalculadoraLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jfCalculadoraLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(btnAC, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 14, Short.MAX_VALUE)));

        jpOperaciones.getAccessibleContext().setAccessibleName("jfCalculadora");

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setActionCommand("btnSalir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuPrincipalLayout = new javax.swing.GroupLayout(jpMenuPrincipal);
        jpMenuPrincipal.setLayout(jpMenuPrincipalLayout);
        jpMenuPrincipalLayout.setHorizontalGroup(
                jpMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                jpMenuPrincipalLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jpMenuPrincipalLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jfCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jfMenuTabs, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)));
        jpMenuPrincipalLayout.setVerticalGroup(
                jpMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpMenuPrincipalLayout.createSequentialGroup()
                                .addComponent(btnSalir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jfCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jfMenuTabs));

        jfCalculadora.getAccessibleContext().setAccessibleName("Calculadora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jpMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1048,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jpMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {
        registrarProducto(txtNombreProducto.getText(), txtUbicacionImgProducto.getText(), txtPrecio.getText());
    }

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalirActionPerformed
        utilPantalla.cambiarPantalla(this, new login());
    }

    private void btnRetrocesoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRetrocesoActionPerformed

        String texto = jtxtOperaciones.getText();
        if (texto.length() > 0) {
            jtxtOperaciones.setText(texto.substring(0, texto.length() - 1));
        }

    }

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtOperaciones.setText(jtxtOperaciones.getText() + "0");
    }

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtOperaciones.setText(jtxtOperaciones.getText() + "00");
    }

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtOperaciones.setText(jtxtOperaciones.getText() + "1");
    }

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtOperaciones.setText(jtxtOperaciones.getText() + "2");
    }

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtOperaciones.setText(jtxtOperaciones.getText() + "3");
    }

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtOperaciones.setText(jtxtOperaciones.getText() + "4");
    }

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtOperaciones.setText(jtxtOperaciones.getText() + "5");
    }

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtOperaciones.setText(jtxtOperaciones.getText() + "6");
    }

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtOperaciones.setText(jtxtOperaciones.getText() + "7");
    }

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtOperaciones.setText(jtxtOperaciones.getText() + "8");
    }

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtOperaciones.setText(jtxtOperaciones.getText() + "9");
    }

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {
        if (!jtxtOperaciones.getText().contains(".")) {
            jtxtOperaciones.setText(jtxtOperaciones.getText() + ".");
        }
    }

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {
        if (resultadoCalculado) {
            jtxtOperaciones.setText(resultadoAnterior + " + "); // Usa el resultado anterior
        } else if (!jtxtOperaciones.getText().isEmpty()) {
            jtxtOperaciones.setText(jtxtOperaciones.getText() + " + "); // Agrega el operador si hay un número
        }
    }

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {
        if (resultadoCalculado) {
            jtxtOperaciones.setText(resultadoAnterior + " - ");
        } else if (!jtxtOperaciones.getText().isEmpty()) {
            jtxtOperaciones.setText(jtxtOperaciones.getText() + " - ");
        }
    }

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {
        if (resultadoCalculado) {
            jtxtOperaciones.setText(resultadoAnterior + " * ");
        } else if (!jtxtOperaciones.getText().isEmpty()) {
            jtxtOperaciones.setText(jtxtOperaciones.getText() + " * ");
        }
    }

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {
        if (resultadoCalculado) {
            jtxtOperaciones.setText(resultadoAnterior + " / ");
        } else if (!jtxtOperaciones.getText().isEmpty()) {
            jtxtOperaciones.setText(jtxtOperaciones.getText() + " / ");
        }
    }

    private void btnACActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtOperaciones.setText(""); // Limpia el campo de operaciones
        jtxtResultados.setText(""); // Limpia el campo de resultados
        numeros.clear(); // Limpia la lista de números
        operadores.clear(); // Limpia la lista de operadores
        resultadoAnterior = 0; // Reinicia el resultado anterior
        resultadoCalculado = false; // Indica que no se ha calculado un resultado
    }

    private void btnPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {
        // Agregar el símbolo de porcentaje al campo de operaciones
        String textoActual = jtxtOperaciones.getText();

        // Si ya se ha calculado un resultado, usarlo como base para el porcentaje
        if (resultadoCalculado) {
            // Usar el resultado anterior como base
            jtxtOperaciones.setText(resultadoAnterior + " % ");
        } else if (!textoActual.isEmpty() && textoActual.matches(".*\\d.*")) {
            // Solo agregar el símbolo si hay un número antes del porcentaje
            jtxtOperaciones.setText(textoActual + " % ");
        }
    }

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {
        // Evaluar la expresión
        String expresion = jtxtOperaciones.getText();
        try {
            double resultado = evaluarExpresion(expresion);
            jtxtResultados.setText("Resultado: " + resultado);
            resultadoAnterior = resultado; // Almacena el resultado
            resultadoCalculado = true; // Indica que se ha calculado un resultado
            jtxtOperaciones.setText(""); // Limpia el campo de operaciones
        } catch (Exception e) {
            jtxtResultados.setText("Error: " + e.getMessage());
        }
    }

    public double evaluarExpresion(String expresion) {
        String[] tokens = expresion.split(" "); // Dividir la expresión por espacios
        Stack<Double> valores = new Stack<>();
        Stack<String> operadores = new Stack<>();

        for (int i = 0; i < tokens.length; i++) {
            String token = tokens[i].trim(); // Eliminar espacios en blanco

            if (token.matches("\\d+(\\.\\d+)?")) { // Si es un número
                valores.push(Double.parseDouble(token));
            } else if (token.equals("+") || token.equals("-") || token.equals("*") || token.equals("/")) {
                while (!operadores.isEmpty() && tienePrecedencia(token, operadores.peek())) {
                    valores.push(realizarOperacion(valores.pop(), valores.pop(), operadores.pop()));
                }
                operadores.push(token);
            } else if (token.equals("%")) {
                // Calcular el porcentaje del número anterior basado en el siguiente número
                if (valores.isEmpty() || i + 1 >= tokens.length || !tokens[i + 1].matches("\\d+(\\.\\d+)?")) {
                    throw new IllegalArgumentException(
                            "Error: Formato incorrecto para calcular el porcentaje.");
                }
                double base = valores.pop(); // Obtener el número base (por ejemplo, 56)
                double porcentaje = Double.parseDouble(tokens[++i]); // Obtener el porcentaje (por ejemplo, 23)
                double resultadoPorcentaje = base * (porcentaje / 100.0); // Calcular el porcentaje
                valores.push(resultadoPorcentaje); // Guardar el resultado en la pila
            }
        }

        // Procesar operadores restantes
        while (!operadores.isEmpty()) {
            valores.push(realizarOperacion(valores.pop(), valores.pop(), operadores.pop()));
        }

        return valores.pop();
    }

    private boolean tienePrecedencia(String operador1, String operador2) {
        if (operador2.equals("(") || operador2.equals(")"))
            return false;
        if ((operador1.equals("*") || operador1.equals("/")) && (operador2.equals("+") || operador2.equals("-")))
            return false;
        return true;
    }

    private double realizarOperacion(double a, double b, String operador) {
        switch (operador) {
            case "+":
                return b + a;
            case "-":
                return b - a;
            case "*":
                return b * a;
            case "/":
                if (a == 0)
                    throw new UnsupportedOperationException("División por cero");
                return b / a;
        }
        return 0;
    }

    private void jtxtOperacionesActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void llenarTablaUsuarios() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nombre de Usuario");
        model.addColumn("Contraseña");

        // Agregar cada usuario a la tabla
        for (Usuario usuario : usuarioList) {
            Object[] row = new Object[3];
            row[0] = usuario.getId(); // Suponiendo que tienes un método getId()
            row[1] = usuario.getNombre(); // Suponiendo que tienes un método getNombre()
            row[2] = usuario.getContraseña(); // Suponiendo que tienes un método getContraseña()
            model.addRow(row);
        }

        // Asignar el modelo a la tabla
        jTableUsuarios.setModel(model);
    }

    private void llenarTablaProductos() {
        try {
            JPanel panelProductos = new JPanel();
            panelProductos.setLayout(new GridLayout(0, 3)); // Cambia 3 por el número de columnas que desees

            // Limpiar el panel antes de llenarlo
            panelProductos.removeAll();

            // Recorrer la lista de productos y agregar cada uno al panel
            for (Producto producto : productoList) {
                // Crear un panel para cada producto
                JPanel panelProducto = new JPanel();
                panelProducto.setLayout(new BoxLayout(panelProducto, BoxLayout.Y_AXIS)); // Usar BoxLayout para apilar
                                                                                         // verticalmente
                panelProducto.setBorder(BorderFactory.createEtchedBorder());
                panelProducto.setPreferredSize(new Dimension(186, 186)); // Ajusta el tamaño según sea necesario

                String ruta = "/src/Imagenes/" + producto.getImagen();

                // Agregar una imagen del producto si tienes la URL
                if (producto.getImagen() != null) {

                    File archivoImagen = new File(ruta);
                    if (!archivoImagen.exists()) {
                        System.out.println(
                                "La imagen " + producto.getNombre() + " no se encuentra en la ruta especificada."
                                        + ruta);
                    } else {
                        ImageIcon imagen = redimensionarImagen(ruta, 100, 100); // Ajusta el tamaño como
                        // desees
                        JLabel lblImagen = new JLabel(imagen);
                        lblImagen.setAlignmentX(JLabel.CENTER_ALIGNMENT); // Centrar la imagen
                        panelProducto.add(lblImagen);
                    }

                }

                // Agregar el nombre del producto
                JLabel lblNombre = new JLabel(producto.getNombre());
                lblNombre.setAlignmentX(JLabel.CENTER_ALIGNMENT); // Centrar el nombre
                panelProducto.add(lblNombre);

                // Agregar el precio
                JLabel lblPrecio = new JLabel("$" + producto.getPrecio());
                lblPrecio.setAlignmentX(JLabel.CENTER_ALIGNMENT); // Centrar el precio
                panelProducto.add(lblPrecio);

                // Agregar el panel del producto al panel principal
                panelProductos.add(panelProducto);
            }

            // Agregar el panel de productos al JScrollPane
            jTabPanelProductos.setViewportView(panelProductos);
            panelProductos.revalidate(); // Actualiza el panel
            panelProductos.repaint(); // Redibuja el panel
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar los productos: " + e.getMessage());
        }
    }

    private ImageIcon redimensionarImagen(String rutaImagen, int ancho, int alto) {
        ImageIcon imagenIcon = new ImageIcon(getClass().getResource(rutaImagen));
        Image imagen = imagenIcon.getImage(); // Obtener la imagen
        Image imagenRedimensionada = imagen.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH); // Redimensionar
        return new ImageIcon(imagenRedimensionada); // Devolver la nueva imagen redimensionada
    }

    private void registrarProducto(String nombre, String ubicacionImg, String precioStr) {
        // Validar que los campos no estén vacíos
        if (nombre.isEmpty() || ubicacionImg.isEmpty() || precioStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que el precio sea un número
        double precio;
        try {
            precio = Double.parseDouble(precioStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio debe ser un número válido.", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que la ubicación de la imagen sea una ruta completa
        File archivoImagen = new File(ubicacionImg);
        if (!archivoImagen.exists() || !archivoImagen.isFile()) {
            JOptionPane.showMessageDialog(this, "La ubicación de la imagen no es válida.", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Llamar al método de la base de datos para registrar el producto
        try {
            dbConnection.registrarProducto(nombre, ubicacionImg, precio);
            JOptionPane.showMessageDialog(this, "Producto registrado con éxito.", "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);
            // Limpiar los campos después de registrar
            txtNombreProducto.setText("");
            txtUbicacionImgProducto.setText("");
            txtPrecio.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al registrar el producto: " + e.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAC;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnPorcentaje;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnRegistrarProducto;
    private javax.swing.JButton btnRetroceso;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSuma;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabPanel;
    private javax.swing.JScrollPane jTabPanelProductos;
    private javax.swing.JPanel jTabPanelRegistro;
    private javax.swing.JPanel jTabPanelUsuarios;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JInternalFrame jfCalculadora;
    private javax.swing.JInternalFrame jfMenuTabs;
    private javax.swing.JPanel jpMenuPrincipal;
    private javax.swing.JPanel jpOperaciones;
    private javax.swing.JPanel jpResultados;
    private javax.swing.JPanel jpResumen;
    private javax.swing.JTextField jtxtOperaciones;
    private javax.swing.JTextField jtxtResultados;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblUbicacionImg;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtUbicacionImgProducto;
    // End of variables declaration//GEN-END:variables
}
